DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES
(
   BRAND_ID INT,
   START_DATE VARCHAR,
   END_DATE VARCHAR,
   PRICE_LIST INT NOT NULL AUTO_INCREMENT,
   PRODUCT_ID INT,
   PRIORITY INT,
   PRICE DECIMAL(10, 2),
   CURR VARCHAR
);